services:
  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
      - user-service
      - user-db

  api-gateway:
    build:
      context: ./api-gateway
      args:
        ENV: development
    container_name: api-gateway
    image: api-gateway-service:latest
    ports:
      - "8001:8000"
    environment:
      - USER_SERVICE_URL=http://user-service:8000
    networks:
      - app-network
    volumes:
      - ./api-gateway:/app
    depends_on:
      - user-service

  user-service:
    build:
      context: ./user-service
      args:
        ENV: development
    image: user-service:latest
    container_name: user-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network
    volumes:
      - ./user-service:/app
    depends_on:
      - user-db

  user-db:
    image: postgres:13
    container_name: user-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  user-data:
