services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8001:8000"
    environment:
      - USER_SERVICE_URL=http://user-service:8000
    networks:
      - app-network
    volumes:
      - ./api-gateway:/app
    depends_on:
      - user-service

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@user-db:5432/users
    networks:
      - app-network
    volumes:
      - ./user-service:/app
    depends_on:
      - user-db

  user-db:
    image: postgres:13
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  user-data:
