services:
  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - api-gateway
      - user-service
      - user-db

  api-gateway:
    build:
      context: ./api-gateway
      args:
        NODE_ENV: production
    image: api-gateway-service-prod:latest
    container_name: api-gateway
    ports:
      - "8001:8000"
    environment:
      - USER_SERVICE_URL=http://user-service:8000
    networks:
      - app-network
    depends_on:
      - user-service

  user-service:
    build:
      context: ./user-service
      args:
        ENV: production
    image: user-service-prod:latest
    container_name: user-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@user-db:5432/users
    networks:
      - app-network
    depends_on:
      - user-db

  user-db:
    image: postgres:13
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  user-data:
