name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push NGINX reverse proxy
      # This image will be used to route traffic to the appropriate microservice
      - name: Build & Push nginx image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          tags: spacemarsx/nginx:latest

      # Build & Push API-Gateway Microservice
      # This image will be used to route traffic to the appropriate microservice
      # and handle authentication
      - name: Build & Push api gateway image
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          push: true
          tags: spacemarsx/api-gateway:latest

      # Build & Push User Microservice
      # This image will be used to handle user-related operations
      - name: Build & Push user image
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          push: true
          tags: spacemarsx/user-service:latest

      # SSH into EC2 and deploy using pulled images
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/trading-platform
            git pull origin main
            docker-compose pull
            docker-compose up -d --remove-orphans
