name: CI/CD DockerHub to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push Auth Microservice
      - name: Build & Push auth image
        uses: docker/build-push-action@v5
        with:
          context: ./auth
          push: true
          tags: spacemarsx/auth:latest

      # Build & Push User Microservice
      - name: Build & Push user image
        uses: docker/build-push-action@v5
        with:
          context: ./user
          push: true
          tags: spacemarsx/user:latest

      # SSH into EC2 and deploy using pulled images
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/your-repo
            git pull origin main
            docker-compose pull  # pulls latest images from DockerHub
            docker-compose up -d --remove-orphans
